### Create User
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "RahulAgrawal"
}

### Get User list
GET http://localhost:5000/users

### Get User By ID
GET http://localhost:5000/users/2

###
POST http://localhost:5000/todos
Content-Type: application/json

{
  "name": "sample2",
	"createdBy": 1,
	"assign": 2,
	"status": ""
}

###
GET http://localhost:5000/todos

### Get todo by ID
GET http://localhost:5000/todos/4

### Get todo by user
GET http://localhost:5000/users/2/todos

###
PUT http://localhost:5000/todos/1
Content-Type: application/json

{
  "name": "sample",
	"status": "Done"
}